FROM python:3.9-slim

WORKDIR /app

# Instala curl para verificar o status do Elasticsearch
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Copia os arquivos necessários
COPY requirements.txt .
COPY docker-examples/elastic-test/data-sample/init_data.sh .
COPY docker-examples/elastic-test/data-sample/generate_customer_data.py .
COPY docker-examples/elastic-test/data-sample/generate_marketing_data.py .

# Torna o script executável
RUN chmod +x init_data.sh

# Executa o script de inicialização
CMD ["./init_data.sh"] 